// <auto-generated />
using Hotel_Listing_Api.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hotel_Listing_Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211104135606_Seeding_Hardcoded_Data")]
    partial class Seeding_Hardcoded_Data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hotel_Listing_Api.DataModel.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "IND",
                            Name = "India"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "CN",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "US",
                            Name = "America"
                        });
                });

            modelBuilder.Entity("Hotel_Listing_Api.DataModel.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1 Near main market",
                            CountryId = 1,
                            Name = "Hotel - 1",
                            Rating = 1.2
                        },
                        new
                        {
                            Id = 2,
                            Address = "2 Near main market",
                            CountryId = 2,
                            Name = "Hotel - 2",
                            Rating = 2.2000000000000002
                        },
                        new
                        {
                            Id = 3,
                            Address = "3 Near main market",
                            CountryId = 3,
                            Name = "Hotel - 3",
                            Rating = 3.2000000000000002
                        },
                        new
                        {
                            Id = 4,
                            Address = "4 Near main market",
                            CountryId = 3,
                            Name = "Hotel - 4",
                            Rating = 4.2000000000000002
                        });
                });

            modelBuilder.Entity("Hotel_Listing_Api.DataModel.Hotel", b =>
                {
                    b.HasOne("Hotel_Listing_Api.DataModel.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
